GET http://localhost:8089/api/default/abc/ 

###

POST http://localhost:8089/api/default/abc HTTP/1.1
content-type: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjoibWlndWVsIiwicm9sZXMiOlsiYmFzaWMiLCJhZG1pbiJdfQ.v0u6CeUcanlNUBcX_rVDRDY2e6NCXshYZ7gHgsUTDKM

{
    "a": 5,
    "b": "hello ;)"
}